import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cx } from "@/utils/styles/cx";
import { Suspense } from "react";

const pretendard = localFont({
  src: "../../public/assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body
        className={cx("p-4 min-h-screen bg-background", pretendard.className)}
      >
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
}
