import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cx } from "@/utils/cx";

const pretendard = localFont({
  src: "../../public/assets/fonts/Pretendard-Regular.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body className={cx("p-4", pretendard.className)}>{children}</body>
    </html>
  );
}
